# Generated by Django 4.2.7 on 2023-11-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cin", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("sex", models.CharField(max_length=1)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "appointmentDesc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PMS.appointment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="patientName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PMS.patient"
            ),
        ),
    ]
