# Generated by Django 4.2.7 on 2023-11-26 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PMS", "0002_rename_appointmentdesc_prescription_appointmentid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="patientName",
            new_name="patientId",
        ),
    ]
